#-------------------------------------------------------------
#
# Modifications Copyright 2020 Graz University of Technology
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#-------------------------------------------------------------

name: Function Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  applicationsTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tests: [
          aggregate,
          append,
          binary.matrix,
          binary.matrix_full_cellwise,
          binary.matrix_full_other,
          binary.scalar,
          binary.tensor,
          blocks,
          builtin,
          caching,
          codegen,
          codegenalg,
          data.misc,
          data.rand,
          data.tensor,
          dnn,
          federated,
          frame,
          indexing,
          io,
          jmlc,
          lineage,
          misc,
          mlcontext,
          nary,
          paramserv,
          parfor,
          quaternary,
          recompile,
          reorg,
          ternary,
          transform,
          unary.matrix,
          unary.scalar,
          updateinplace,
          vect
          ]
        os: [ubuntu-latest]
        java: [ 1.8 ]
    name:  Func Test ${{ matrix.tests }} 
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Maven clean, compile & test-compile
      run: mvn clean compile test-compile

    - name: install R
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/"
        sudo apt update
        sudo apt install r-base
    
    - name: set R environment
      run: |
        echo "R_LIBS=/tmp/Rpackages/" > ~/.Renviron
        mkdir /tmp/Rpackages

    - name: install R Dependencies
      # TODO: Find out how to make if statement correctly: suggestion but not working: if: ${{ matrix.tests }} == P
      run: Rscript ./src/test/scripts/installDependencies.R "/tmp/Rpackages/"

    - name: Run all tests starting with "${{ matrix.tests }}"
      run: mvn surefire:test -DskipTests=false -Dtest=org.tugraz.sysds.test.functions.${{ matrix.tests }}.**
