name: Function Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  applicationsTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        tests: [
          aggregate,
          append,
          binary.matrix,
          binary.matrix_full_cellwise,
          binary.matrix_full_other,
          binary.scalar,
          binary.tensor,
          blocks,
          builtin,
          caching,
          codegen,
          codegenalg,
          data,
          dnn,
          federated,
          frame,
          indexing,
          io,
          jmlc,
          lineage,
          misc,
          mlcontext,
          nary,
          paramserv,
          parfor,
          quaternary,
          recompile,
          reorg,
          ternary,
          transform,
          unary.matrix,
          unary.scalar,
          updateinplace,
          vect
          ]
        os: [ubuntu-latest]
        java: [ 1.8 ]
    name:  Func Test ${{ matrix.tests }} 
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: clean, compile & test-compile
      run: mvn clean compile test-compile

    - name: install R
      run: sudo apt -y install r-base
    
    - name: set R environment
      run: |
        echo "R_LIBS=/tmp/Rpackages/" > ~/.Renviron
        mkdir /tmp/Rpackages

    - name: install R Dependencies
      # TODO: Find out how to make if statement correctly: suggestion but not working: if: ${{ matrix.tests }} == P
      run: Rscript ./src/test/scripts/installDependencies.R "/tmp/Rpackages/"

    - name: Run all tests starting with "${{ matrix.tests }}"
      run: mvn surefire:test -DskipTests=false -Dtest=org.tugraz.sysds.test.functions.${{ matrix.tests }}.**
